name: Build and Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Memberikan izin kepada Action untuk menulis kembali ke repositori.
    # Ini diperlukan agar langkah 'git push' berhasil.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build static files
        run: node build.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # Baris di bawah ini memeriksa apakah ada perubahan sebelum mencoba commit & push
          git diff --quiet && git diff --staged --quiet || (git commit -m "Build: auto-generate site files" && git push)
